### ISSUE TITLE
/vdirsyncer

### ISSUE THREAD

**Issue by hobarrera** [pimutils/vdirsyncer#364]
A while ago, we briefly discussed moving vdirsyncer/khal/todoman under a single namespace `/vdirsyncer`.
There was also an intention of sharing common code (vdirsyncer/python-vdir).

The idea sort of got abandoned, and I'd like to revisit it a bit.

There's also some code improvements that can result of using python-vdir - eg: both khal and todoman need to read and print colours from vdirs. Khal works, which todoman is slightly broken. I'd much rather have this code in a single, shared dependency, and avoid copy-pasting it.

cc: @untitaker @geier

**Comment by untitaker** [comment]
>A while ago, we briefly discussed moving vdirsyncer/khal/todoman under a single namespace /vdirsyncer.

I would've already done if I knew of a good name for the organization. "vdirsyncer" is not it IMO, but if you two don't care I'll not veto.

>There was also an intention of sharing common code (vdirsyncer/python-vdir).

Next steps would be

* preparing PRs that make todoman/khal depend on that package (just depend on the git repo)
* take more and more code out of todoman/khal and move it into the package, polish its API
* Release package on PyPI, change dependency accordingly, merge PRs

**Comment by untitaker** [comment]
I've come to the realization that it's probably not a good idea for vdirsyncer to depend on python-vdir. The reason is that the main thing vdirsyncer cares about is the uniformity of the APIs of all storage types. The prettyness of the API is not important. OTOH, python-vdir definetly should focus on the usecases of khal/todoman, and that definetly includes a pretty API.

**Comment by untitaker** [comment]
I just tried to port todoman to python-vdir. It turns out python-vdir as-is isn't saving any code in todoman either. I'd like to say that vdir is already a very simple format (probably true), but seriously, python-vdir / filesystem storage is such a primitive piece of code once you remove all the requirements vdirsyncer has for its internal storage API.

Even if you add a lot of helper methods that make e.g. parsing colors easier (`storage.get_color().rgb` was the last thing I implemented), you might not cover the usecase for everybody. The other users will fall back to manual parsing.

I've come to the conclusion that using python-vdir in todoman would be a Java-esque abstraction to implement (i.e. complete overkill in class fiddling). Therefore I'd like to pause that effort for a moment, and focus on getting todoman, khal and vdirsyncer under one org (which is what I actually care about).

**Comment by geier** [comment]
While I'm not against it, I don' like `vdirsyncer` as the org name.
Couldn't come up with a better one either though.

Quoting Hugo Osvaldo Barrera (2016-03-05 09:29:18)

**Comment by untitaker** [comment]
I wonder if we should move the repos before getting indefinetly hung up about the org name, and rename later. We should experiment how GitHub's redirecting stuff works in that case though.

**Comment by hobarrera** [comment]
Repo ideas:

 * Something with `pim` in it.
 * Something with `vdir` in it.
 * Just any random name (eg: a tree name, a bird's name, etc).

The latter might be simplest, and won't tie us to any specific technology (though all apps currently share in common that we use `vdir` as a main backend).

**Comment by geier** [comment]
Perhaps we can find a bird's, tree's or something else's name with `pim` or `vdir` in it?

**Comment by hobarrera** [comment]
> Perhaps we can find a bird's, tree's or something else's name with pim or vdir in it?

I like the idea, but the wikipedia lists for both categories seem to indicate there aren't any. :(

**Comment by untitaker** [comment]
The other idea that's come up in IRC is "pimutils", analogous to coreutils.

Busybox would've been an awesome name too, given that half of vdirs are about task and time planning. But that name is taken, obviously.

**Comment by hobarrera** [comment]
> The other idea that's come up in IRC is "pimutils", analogous to coreutils.

There's just some Java class out these with that name, otherwise, there are no references to it, so it's pretty much usable.

**Comment by geier** [comment]
pimguin :)

Quoting Hugo Osvaldo Barrera (2016-03-11 11:33:14)

**Comment by untitaker** [comment]
As in, PIM and GUI? :)

**Comment by hobarrera** [comment]
`pimutils` was mentioned on IRC, and I liked it. Do we have consensus?

**Comment by untitaker** [comment]
From my side yes. @geier?

**Comment by geier** [comment]
I'm good with pimutils.


Quoting Markus Unterwaditzer (2016-03-15 02:20:36)

**Comment by untitaker** [comment]
***It's happening!***

I've created https://github.com/pimutils and moved the `python-vdir` and `todoman` repo over. Will move vdirsyncer asap.

I'm playing with the thought of having the testservers still live on the vdirsyncer org for cleaner namespace.

**Comment by untitaker** [comment]
I think I finished the migration for vdirsyncer.

## Flattr

I had to recreate the Flattr page, since it's unable to follow redirects properly. This means that there is now:

* https://flattr.com/thing/42384d454fdae6a3b7ad4c06281f4f4a
* https://flattr.com/thing/2956614

I'll ask support about this.

## Bountysource

Bountysource followed the redirect automatically and preserved all data (also my money, phew)

## Travis

Travis followed redirects and preserved build history.

## Codecov

Same as Travis.

## Waffle.io

Waffle.io crapped itself while trying to find the nonexistent untitaker/vdirsyncer. I created a new project, but can't delete the old one because it's full of JS errors and unrendered Mustache templates. I contacted support.

**Comment by untitaker** [comment]
I've also created https://github.com/pimutils/meta/issues for organizational matters, if we need it...

**Comment by hobarrera** [comment]
FWIW, I've now updated todoman, and pointed all references to pimutils/todoman. PyPI will refresh on the next release.
