### ISSUE TITLE
Catch when uploading an empty file

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/vdirsyncer#578]
(Maybe also files that are **clearly** not icalendar files?)

See #577

**Comment by untitaker** [comment]
Concretely, `Item.__init__` should raise an exception when the given string (`raw`) only contains whitespace.

**Comment by hobarrera** [comment]
Dunno if we should raise, or merely skip it (or emit a warning).

**Comment by untitaker** [comment]
Yeah, just realized that this is harder.

**Comment by untitaker** [comment]
Ok I think I have an idea: When copying the item from A to B, we call `Item.sanity_check` which does all these validations and raises exceptions if e.g. `self.raw` is only whitespace. Because at this point we already have proper exception handling that skips failed uploads, but doesn't ignore them in the exit code at the end.

**Comment by untitaker** [comment]
The sanity check can be called in `Action.run` before `_run_impl` is called.

**Comment by hobarrera** [comment]
Yup, that sounds pretty good.
