### ISSUE TITLE
vdirsyncer breaks on 404 not found

### ISSUE THREAD

**Issue by stevenroose** [pimutils/vdirsyncer#652]
I get this 404 NOT FOUND error while syncing. 
https://gist.github.com/stevenroose/67805c6aca72a1b9e42bf5d0f11b2237

My calendar is on Fruux(.com), but I used Thunderbird before where I also had a Google Calendar. I think somehow a reference to a Google Calendar item must have slipped into my Fruux data and vdirsyncer cannot handle that. 

`vdirsyncer repair` gets the same error. Shouldn't there be a way for vdirsync to recover from this issue in a way by f.e. ignoring the ones he can't find? Now I have this error on a CalDAV server I can't access manually and no way to recover from it.

**Comment by untitaker** [comment]
Fruux should still return the items which are available (and not fail on the whole request), so that's a bug IMO

Ignoring the error is not a good strategy IMO since it is equal to ignoring misbehavior of the server (listing an event when vdirsyncer attempts to enumerate all events, but then 404ing on it when attempting to fetch it) and ignoring/skipping items is equal to losing it.

Please contact fruux support.

On 18 July 2017 17:29:37 GMT+02:00, Steven Roose <notifications@github.com> wrote:
>I get this 404 NOT FOUND error while syncing. 
>https://gist.github.com/stevenroose/67805c6aca72a1b9e42bf5d0f11b2237
>
>My calendar is on Fruux(.com), but I used Thunderbird before where I
>also had a Google Calendar. I think somehow a reference to a Google
>Calendar item must have slipped into my Fruux data and vdirsyncer
>cannot handle that. 
>
>`vdirsyncer repair` gets the same error. Shouldn't there be a way for
>vdirsync to recover from this issue in a way by f.e. ignoring the ones
>he can't find? Now I have this error on a CalDAV server I can't access
>manually and no way to recover from it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/652

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stevenroose** [comment]
I contacted Fruux, so I hope they'll follow up.
