### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by nim65s** [pimutils/vdirsyncer#669]
Hi,

Did anyone managed to get things work with thunderbird ?

#490 shows that it can work for events by having two pairs, one caldav/singlefile for TB and another caldav/filesystem for other programs.

But for contacts, you can only import / export, and can't synchronize with something on your filesystem.

Any idea ?

**Comment by untitaker** [comment]
I'd actually strongly recommend to use Thunderbird addons (https://help.hover.com/hc/en-us/articles/217282057-CalDAV-and-CardDAV-Synchronization-for-Thunderbird) for this. I suppose that @dmacivar pointed vdirsyncer to internal files of Thunderbird, which seems risky to me.

**Comment by axet** [comment]
I think this is a feature request. We need Thunderbird Addon (or direct source modification) which can read address book from filesystem single file or directory.

Right now I have shared emails between Thunderbird, Evolution using maildir. But I'm missing shared contacts and calendar events. To make it work I put all my mails into ~/mails directory with simple folder + emails structure. But since Evolution and Thunderbird has its own maildir structure I wrote simple bash script which create symbolic links to my main mail storage and booth apps are working perfectly with shared emails. For anyone who needs it here they are (yes I have could + encryption but this is another story):

* https://gitlab.com/axet/homebin/-/blob/debian/encfscfg.d/mailcfg-evolution.sh
* https://gitlab.com/axet/homebin/-/blob/debian/encfscfg.d/mailcfg-thunderbird.sh

I see no other solution, but having vdirsyncer support from all software like Evolution, Thunderbird, Android. Partial support (like CardDAV/CalDAV servers not going to work)
