### ISSUE TITLE
Two factor authentication not supported

### ISSUE THREAD

**Issue by AtomToast** [pimutils/vdirsyncer#810]
- vdirsyncer version: 0.16.7
- server software: Nextcloud 17.0.2
- python version: 3.8.1
- operating system: Arch Linux
- my config file: https://pastebin.com/n6AhCCiX
- my debug output: https://pastebin.com/sfsPyRsd

When enabling 2fa vdirsyncer returns a password login forbidden on any action that requires authentication.  
There is no issue like this with nextcloud-desktop or DAVX5 on my phone.

**Comment by zachdecook** [comment]
I believe DAVX5 uses the nextcloud files app to generate an application-specific password. I think nextcloud-desktop works the same way, but pops up a browser window for the login.

Since vdirsyncer is a command-line application, I don't think either of these is an option.

Have you tried setting an application-specific password at https://cloud.example.com/settings/user/security

**Comment by AtomToast** [comment]
oh, nice. I never actually noticed that section since it's so hidden.  
That resolves the issue quite easily.  
Since this seems to be the easiest option I think I'll close this issue now
